context:
  name: lerna
  version: "2.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 37b28573a6605a72ff64a1d8d4554af64d7f640db076d0ad4a7ff29d3ea15278

build:
  number: 0
  python:
    version_independent: true
  script:
    - if: unix
      then: export PYO3_PYTHON="$PYTHON"
      else: set "PYO3_PYTHON=%PYTHON%"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: is_abi3 and not is_python_min

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - hatchling
    - hatch-rs
    - if: is_abi3
      then:
      - python-abi3
  run:
    - python
    - omegaconf >=2.2.3,<2.4
    - packaging
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      imports:
        - lerna
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: |
    A high-performance configuration framework for Python applications, built with Rust.
    Lerna is a rewrite of Facebook's Hydra configuration framework.
  homepage: https://github.com/nbprint/lerna
  repository: https://github.com/nbprint/lerna

extra:
  recipe-maintainers:
    - timkpaine
